
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 22 16:26:46 CST 2020
//----------------------------------------------------

package analizador_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REL_OP = 6;
  public static final int OTHERWISE = 24;
  public static final int WHEN = 30;
  public static final int FUNCTION = 4;
  public static final int RIGHT_BRACKET = 11;
  public static final int MULT_OP = 18;
  public static final int OUTPUT = 22;
  public static final int INPUT = 21;
  public static final int ADD_OP = 17;
  public static final int NOT = 20;
  public static final int AND = 14;
  public static final int TYPE = 16;
  public static final int IN = 26;
  public static final int OR = 15;
  public static final int COMMA = 7;
  public static final int BOOL_VAL = 34;
  public static final int LEFT_BRACE = 12;
  public static final int RIGHT_PARENTHESIS = 9;
  public static final int NUM = 3;
  public static final int NEXT = 27;
  public static final int LOOP = 25;
  public static final int ASSIGN = 5;
  public static final int IF = 23;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int END_CODE_BLOCK = 29;
  public static final int RIGHT_BRACE = 13;
  public static final int COLON = 32;
  public static final int EXP_OP = 19;
  public static final int NEW_LINE = 2;
  public static final int END = 33;
  public static final int INIT_CODE_BLOCK = 28;
  public static final int CHR_VAL = 35;
  public static final int LEFT_BRACKET = 10;
  public static final int LEFT_PARENTHESIS = 8;
  public static final int DO = 31;
}

